### ISSUE TITLE
broken test with MySQL and AR 4.2

### ISSUE THREAD

**Issue by mceachen** [ClosureTree/with_advisory_lock#24]
With the last merge: https://travis-ci.org/ClosureTree/with_advisory_lock/jobs/255309283

```
NoMethodError:         NoMethodError: undefined method `can_be_bound?' for ActiveRecord::PredicateBuilder:Class
...
4.2.9/lib/active_record/relation/query_methods.rb:574:in `where'
            /home/travis/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.9/lib/active_record/querying.rb:10:in `where'
            /home/travis/build/ClosureTree/with_advisory_lock/test/parallelism_test.rb:28:in `block in work'
```

(perhaps skip that one test if AR 4.2 and MySQL?)

**Comment by mceachen** [comment]
EW! I restarted the 2 broken builds (both MySQL versions with AR 4.2) and they both passed, so it's a flaky test or a flaky CI. Either way, ew.

Closing for now.
